[package]
name = "audio-bridge-types"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
utoipa = { version = "5.4.0", optional = true, features = ["actix_extras"] }

[features]
openapi = ["utoipa"]
