[package]
name = "audio-hub-server"
version = "0.1.1"
edition = "2024"
build = "build.rs"
repository = "https://github.com/dariusbakunas/audio-bridge.git"

[dependencies]
actix-web = "4.11.0"
anyhow = { workspace = true }
audio-bridge-proto = { path = "../audio-bridge-proto" }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
symphonia = { workspace = true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
ctrlc = { workspace = true }
utoipa = { version = "5.4.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
toml = "0.9.11+spec-1.1.0"
ureq = { version = "3.1.4", features = ["json"] }
mdns-sd = "0.17.2"

[build-dependencies]
time = { version = "0.3", features = ["formatting"] }
