[package]
name = "audio-hub-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
anyhow = { workspace = true }
audio-bridge-proto = { path = "../audio-bridge-proto" }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
symphonia = { workspace = true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
ctrlc = { workspace = true }
utoipa = { version = "4.2.3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["actix-web"] }
toml = "0.8.23"
ureq = { version = "2.10.1", features = ["json"] }
